#!/bin/bash
TOOL_NAME=$0
usage() 
{
    echo "usage: $TOOL_NAME [OPTION...]
  -l, --local       generate local html pages (as opposed to a deployable website)"
}

error()
{
    echo $1 
    exit 1
}

check()
{
    message=$1
    shift 
    echo $@
    "$@" || error "$message"
}

local=
while [ "$1" != "" ] ; do
    case $1 in 
    -l | --local ) 
        shift
        local="local"
        ;;
    * )
        usage 
        exit 1
    esac 
    shift 
done 

base=$PWD

mkdir -p .entrapta/ 
cd .entrapta/

if ! [ -d entrapta ]; then
    git clone https://github.com/kelvin13/entrapta 
else 
    cd entrapta 
    git pull 
    cd ..
fi 

cd entrapta/ 

swift build -c release

if [ -z $local ]; then 
    .build/release/entrapta ../../sources/png/*.swift --directory ../../documentation/ --url-prefix https://kelvin13.github.io/png --github https://github.com/kelvin13/png --project Swift\ JPEG\ Documentation
else 
    .build/release/entrapta ../../sources/png/*.swift --directory ../../documentation/ --url-prefix $base/documentation --url-suffix /index.html --github https://github.com/kelvin13/png --project Swift\ JPEG\ Documentation
fi 

cd ../../
