#!/bin/bash
set -euo pipefail

swift --version
swift package dollup --allow-writing-to-package-directory
git diff --exit-code

swift build
swift build -c release
#  Debug-only tests
swift test -c debug --filter LZ77Tests
swift test -c debug --filter PNGTests
#  All tests
swift test -c release --no-parallel
