name: Android

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: 💖 Checkout repository 💖
                uses: actions/checkout@v6

            -   name: 💖 Run tests 💖
                uses: skiptools/swift-android-action@v2
