name: build-windows

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    windows:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [windows-2022, windows-2019]
                swift: [5.6.2]
        steps:
            -   name: checkout 
                uses: actions/checkout@v2
            
            -   name: toolchain 
                uses: compnerd/gha-setup-swift@v0.0.1
                with:
                    branch: swift-${{ matrix.swift }}-release
                    tag: ${{ matrix.swift }}-RELEASE
            -   name: build 
                run: |
                    swift --version
                    swift build
            -   name: test 
                run: |
                    swift --version
                    swift run -c debug PNGTests
                    swift run -c release PNGIntegrationTests
                    swift run -c release PNGCompressionTests
