name: Tests

permissions:
    contents: write
on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    changes:
        runs-on: ubuntu-latest
        name: Assess changes
        steps:
            -   name: 💖 Checkout repository 💖
                uses: actions/checkout@v6

            -   name: 💖 Decide checks 💖
                uses: tj-actions/changed-files@v47
                id: changes
                with:
                    files_ignore: |
                        README.md
                        LICENSE
                        NOTICE
                        .mailmap
                        .gitignore
                        .github/FUNDING.yml
        outputs:
            code_changed: ${{ steps.changes.outputs.any_changed }}

    Linux:
        runs-on: ubuntu-24.04
        name: Ubuntu 24.04
        needs: changes
        if: ${{ needs.changes.outputs.code_changed == 'true' }}
        steps:
            -   name: 💖 Install Swift 💖
                uses: rarestype/swift-install-action@v1
                with:
                    swift-prefix: "swift-6.3-release/ubuntu2404/swift-6.3-RELEASE"
                    swift-id: "swift-6.3-RELEASE-ubuntu24.04"

            -   name: 💖 Checkout repository 💖
                uses: actions/checkout@v6

            -   name: 💖 Run tests 💖
                run: Scripts/TestAll

            -   name: 💖 Update badge 💖
                uses: rarestype/rarestbadge@v1
                if: always()

    macOS:
        runs-on: macos-26
        needs: changes
        if: ${{ needs.changes.outputs.code_changed == 'true' }}
        steps:
            -   name: 💖 Checkout repository 💖
                uses: actions/checkout@v6

            -   name: 💖 Select Xcode 26.4 💖
                run: sudo xcode-select -s /Applications/Xcode_26.4.app/Contents/Developer

            -   name: 💖 Run tests 💖
                run: Scripts/TestAll

            -   name: 💖 Update badge 💖
                uses: rarestype/rarestbadge@v1
                if: always()

    macOS-devices:
        strategy:
            matrix:
                destination: [iOS, tvOS, visionOS, watchOS]
        needs: changes
        if: ${{ needs.changes.outputs.code_changed == 'true' }}
        name: ${{ matrix.destination }}
        uses: rarestype/swift-device-action/.github/workflows/build.yml@v1
        with:
            xcode-scheme: 'PNG'
            destination: ${{ matrix.destination }}
            badge-namespace: ${{ github.workflow }}

    Android:
        needs: changes
        if: ${{ needs.changes.outputs.code_changed == 'true' }}
        runs-on: ubuntu-latest
        steps:
            -   name: 💖 Checkout repository 💖
                uses: actions/checkout@v6

            -   name: 💖 Run tests 💖
                uses: skiptools/swift-android-action@v2
                with:
                    copy-files: Sources Tests

            -   name: 💖 Update badge 💖
                uses: rarestype/rarestbadge@v1
                if: always()
